In [1]:
!pip install librosa

In [2]:
import sklearn
import pandas as pd
import librosa
import numpy as np

In [3]:
import os

In [186]:
li=os.listdir("dataverse_files")

In [187]:
li

['YAF_wire_happy.wav',
 'OAF_fat_disgust.wav',
 'OAF_bought_happy.wav',
 'OAF_fit_neutral.wav',
 'YAF_dead_fear.wav',
 'OAF_join_neutral.wav',
 'YAF_hall_happy.wav',
 'YAF_hurl_neutral.wav',
 'OAF_king_angry.wav',
 'OAF_rot_angry.wav',
 'YAF_hit_ps.wav',
 'OAF_gaze_sad.wav',
 'YAF_ripe_fear.wav',
 'YAF_dog_neutral.wav',
 'OAF_hire_angry.wav',
 'OAF_neat_sad.wav',
 'YAF_gin_happy.wav',
 'YAF_sub_neutral.wav',
 'OAF_mouse_sad.wav',
 'OAF_ripe_disgust.wav',
 'YAF_date_disgust.wav',
 'YAF_hall_fear.wav',
 'OAF_voice_disgust.wav',
 'YAF_laud_neutral.wav',
 'YAF_numb_angry.wav',
 'YAF_cause_fear.wav',
 'YAF_seize_angry.wav',
 'YAF_rag_disgust.wav',
 'OAF_take_angry.wav',
 'OAF_page_sad.wav',
 'YAF_dime_sad.wav',
 'OAF_ripe_ps.wav',
 'YAF_pick_angry.wav',
 'OAF_take_ps.wav',
 'OAF_calm_angry.wav',
 'OAF_third_fear.wav',
 'OAF_fall_neutral.wav',
 'OAF_pain_ps.wav',
 'YAF_shack_neutral.wav',
 'OAF_yes_fear.wav',
 'YAF_love_happy.wav',
 'YAF_raise_disgust.wav',
 'OAF_peg_happy.wav',
 'YAF_gaze_h

In [188]:
li[0].split("_")[2]  #angry-0, neutral-1, disgust-2, sad-3, fear-4, happy-5, ps-6

'happy.wav'

In [190]:
li_1=[]
for i in li:
    if i.split("_")[2]=="angry.wav":
        li_1.append((i,0))
    if i.split("_")[2]=="neutral.wav":
        li_1.append((i,1))
    if i.split("_")[2]=="disgust.wav":
        li_1.append((i,2))
    if i.split("_")[2]=="sad.wav":
        li_1.append((i,3))
    if i.split("_")[2]=="fear.wav":
        li_1.append((i,4))
    if i.split("_")[2]=="happy.wav":
        li_1.append((i,5))
    if i.split("_")[2]=="ps.wav":
        li_1.append((i,6))
    

In [17]:
sum=[0,0,0,0,0,0]

for i in li_1:
    if i[1]==0:
        sum[0]=sum[0]+1
    if i[1]==1:
        sum[1]=sum[1]+1
    if i[1]==2:
        sum[2]=sum[2]+1
    if i[1]==3:
        sum[3]=sum[3]+1
    if i[1]==4:
        sum[4]=sum[4]+1
    if i[1]==5:
        sum[5]=sum[5]+1
    

print(sum)
        

[1271, 1087, 1271, 1271, 1271, 1271]


In [191]:
librosa.load("dataverse_files/"+li_1[0][0])

(array([ 0.00049374, -0.0004413 , -0.00010213, ...,  0.00163774,
         0.00113232,  0.        ], dtype=float32),
 22050)

In [192]:
import IPython.display as ipd
ipd.Audio("dataverse_files/"+li_1[0][0])

In [25]:
b=librosa.feature.mfcc(librosa.load("AudioWA/"+li_1[0][0])[0],n_mfcc=13)

In [28]:
c=librosa.feature.delta(b, order=1)

In [29]:
d=librosa.feature.delta(b, order=2)

In [30]:
c.shape

(13, 105)

In [32]:
np.mean(c,axis=1).shape

(13,)

In [193]:
final_arr=[]
j=0
for i in range(len(li_1)):
    mfcc=librosa.feature.mfcc(librosa.load("dataverse_files/"+li_1[i][0])[0],n_mfcc=13)
    mfcc_delta=librosa.feature.delta(mfcc, order=1)
    mfcc_delta_delta=librosa.feature.delta(mfcc, order=2)
    final_arr.append((np.mean(mfcc,axis=1),np.mean(mfcc_delta,axis=1),np.mean(mfcc_delta_delta,axis=1),li_1[i][1]))
    j=j+1
    print(j)
    
    


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061


In [194]:
pd.DataFrame(final_arr)

0  \
0     [-300.55713, 41.210747, -28.552607, 18.15966, ...   
1     [-427.0029, 71.92068, 2.4389596, -9.97249, 13....   
2     [-441.80252, 92.96893, 18.334127, -13.860087, ...   
3     [-515.4028, 60.01885, 16.055157, 11.45487, 16....   
4     [-294.87326, 42.45468, -16.164543, 16.63923, 0...   
...                                                 ...   
2795  [-535.6558, 82.13634, 31.404861, 10.432503, 18...   
2796  [-417.7793, 47.11415, 4.0274014, 1.1409129, -6...   
2797  [-498.9032, 86.57726, 19.229626, 4.3090787, 6....   
2798  [-458.42746, 75.567665, 13.048701, -2.6875916,...   
2799  [-457.89777, 81.75872, 12.312971, -4.9471307, ...   

                                                      1  \
0     [-0.24599496, 1.6126705, -0.45193884, 0.331377...   
1     [1.3238181, -0.40825215, -0.30371517, -0.19462...   
2     [1.19772, 2.5643394, -0.75773114, -0.74843484,...   
3     [5.2163186, 0.5335587, -0.3829182, -0.54767174...   
4     [-0.97503746, 1.8440909, -0.71109354, 0.476230...   
...                                                 ...   
2795  [-1.4596978, 1.430461, 0.4585351, 0.023894288,...   
2796  [-0.87347984, 2.5445714, 0.7827484, -0.6463631...   
2797  [1.2121615, 0.6421356, 0.53114796, 0.119167306...   
2798  [-2.3566184, 0.5811907, -0.52663213, 0.3076250...   
2799  [-0.26530915, 0.9978187, 0.64829665, 0.2869350...   

                                                      2  3  
0     [-0.60070175, -0.033920813, 0.045489185, 0.233...  5  
1     [-1.215047, 0.57430685, -0.24031994, -0.087143...  2  
2     [-1.1891031, -0.1635238, -0.14601438, 0.274595...  5  
3     [-0.44603565, 0.38684103, 0.32565323, -0.08007...  1  
4     [-0.6363856, 0.38821688, 0.092769146, 0.308947...  4  
...                                                 ... ..  
2795  [-0.8651458, 0.011959979, -0.07721819, 0.15223...  3  
2796  [-1.9165511, 0.2737881, -0.47004047, 0.2074719...  4  
2797  [-1.2883259, 0.14216699, 0.10259294, -0.094711...  1  
2798  [0.5420677, 0.25129974, -0.3986509, 0.04302660...  5  
2799  [-0.6737847, 0.07898373, -0.2682586, 0.0863678...  2  

[2800 rows x 4 columns]

In [40]:
pd.DataFrame(final_arr).to_csv("data.csv")

In [43]:
pd.read_csv("data.csv")

Unnamed: 0                                                  0  \
0              0  [-266.32425     109.04992      -3.2035615    4...   
1              1  [-346.57297     126.04892      10.193129     5...   
2              2  [-421.81848    141.25726      1.620359    57.0...   
3              3  [-4.1359122e+02  1.4145085e+02  1.1928319e+01 ...   
4              4  [-416.2484     137.46568     13.514902    61.0...   
...          ...                                                ...   
7437        7437  [-279.37042     77.42549     -7.1757197   36.6...   
7438        7438  [-286.81268    126.56644    -12.595298    30.3...   
7439        7439  [-3.2922260e+02  1.1139811e+02  1.1386372e+01 ...   
7440        7440  [-3.4896472e+02  1.1783241e+02  5.6132102e+00 ...   
7441        7441  [-436.06827    132.55522      8.9359665   48.6...   

                                                      1  \
0     [-0.91489685  0.38143703  0.49954724 -0.334310...   
1     [-0.14344136 -0.07112371  0.02789582  0.001875...   
2     [-0.11429247  0.02015067  0.04332326 -0.003229...   
3     [-0.16917278 -0.06258024  0.0402808   0.061710...   
4     [ 0.04348734  0.0104669   0.03831414  0.053166...   
...                                                 ...   
7437  [ 3.55088532e-01 -2.07143232e-01 -1.62545696e-...   
7438  [ 0.3917787   0.0701824  -0.4212236  -0.153051...   
7439  [-0.1051406  -0.12830931 -0.07648469 -0.012611...   
7440  [-0.16073032 -0.0982111   0.02426622 -0.007311...   
7441  [ 0.11556509  0.02197695 -0.04502672  0.029440...   

                                                      2  3  
0     [ 0.15699692  0.01849905 -0.06570897  0.005581...  0  
1     [-0.07624339 -0.00640954  0.01653408  0.023754...  0  
2     [-0.08437949 -0.00389113 -0.00812952 -0.061379...  1  
3     [-0.04146709 -0.11413106 -0.10432833  0.029253...  1  
4     [ 0.02933306  0.01736187 -0.04099881 -0.011809...  2  
...                                                 ... ..  
7437  [-5.4112971e-01  1.5551338e-01  1.9229184e-01 ...  0  
7438  [ 0.14569733  0.06477235 -0.14966556 -0.164858...  0  
7439  [-0.07126915 -0.05871441 -0.00875974  0.002884...  0  
7440  [-0.07465805 -0.04026205 -0.0241583   0.004421...  0  
7441  [-0.06741118 -0.03665718 -0.02308898 -0.057082...  1  

[7442 rows x 5 columns]

In [195]:
df1=pd.DataFrame(final_arr)

In [196]:
df1[0].values

array([array([-300.55713  ,   41.210747 ,  -28.552607 ,   18.15966  ,
        -12.053949 ,  -13.01452  ,   -7.4745355,  -16.613626 ,
          4.5967813,   -5.050444 ,  -12.797876 ,   13.399601 ,
        -17.155336 ], dtype=float32),
       array([-4.2700290e+02,  7.1920677e+01,  2.4389596e+00, -9.9724903e+00,
        1.3015941e+01,  6.2493258e+00, -1.6573395e+01,  4.3356511e-01,
       -1.1927688e+01,  6.2564421e-01, -2.7245252e+00, -3.4905396e+00,
       -4.1496301e-01], dtype=float32),
       array([-441.80252  ,   92.96893  ,   18.334127 ,  -13.860087 ,
         -4.9424043,    3.4623353,  -10.084094 ,    2.9872322,
        -16.89864  ,   -4.808069 ,  -10.294229 ,   -9.524105 ,
         -6.3364987], dtype=float32),
       ...,
       array([-498.9032   ,   86.57726  ,   19.229626 ,    4.3090787,
          6.9963493,   11.253559 ,   -2.563979 ,   -7.8557954,
        -12.648978 ,   -4.6071496,  -14.912954 ,    1.5475438,
         -5.4736614], dtype=float32),
       array([-4.5842746e+

In [197]:
final_arr

[(array([-300.55713  ,   41.210747 ,  -28.552607 ,   18.15966  ,
          -12.053949 ,  -13.01452  ,   -7.4745355,  -16.613626 ,
            4.5967813,   -5.050444 ,  -12.797876 ,   13.399601 ,
          -17.155336 ], dtype=float32),
  array([-0.24599496,  1.6126705 , -0.45193884,  0.33137754,  0.19164087,
         -0.01619034, -0.13693911,  0.03453985,  0.3107135 , -0.23686235,
         -0.27860636, -0.20650755, -0.19917117], dtype=float32),
  array([-0.60070175, -0.03392081,  0.04548918,  0.23329352, -0.0292945 ,
          0.05877737,  0.04984563,  0.18591644,  0.00431228,  0.01288244,
          0.03744461, -0.04284052,  0.0538797 ], dtype=float32),
  5),
 (array([-4.2700290e+02,  7.1920677e+01,  2.4389596e+00, -9.9724903e+00,
          1.3015941e+01,  6.2493258e+00, -1.6573395e+01,  4.3356511e-01,
         -1.1927688e+01,  6.2564421e-01, -2.7245252e+00, -3.4905396e+00,
         -4.1496301e-01], dtype=float32),
  array([ 1.3238181 , -0.40825215, -0.30371517, -0.19462167, -0.16345294

In [198]:
final_arr_1=[]

for i in final_arr:
    arr=[]
    for j in i[0]:
        arr.append(j)
    for j in i[1]:
        arr.append(j)
    for j in i[2]:
        arr.append(j)
    arr.append(i[3])
    final_arr_1.append(arr)

In [199]:
pd.DataFrame(final_arr_1).to_csv("data.csv")

In [200]:
df1=pd.read_csv("data.csv")

In [201]:
df1["39"]

0       5
1       2
2       5
3       1
4       4
       ..
2795    3
2796    4
2797    1
2798    5
2799    2
Name: 39, Length: 2800, dtype: int64

In [202]:
y=df1["39"].values

In [203]:
y

array([5, 2, 5, ..., 1, 5, 2])

In [211]:
x=df1.drop('39', 1)

<ipython-input-211-536e762050c8>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x=df1.drop('39', 1)


In [205]:
x=x.values

In [212]:
x

Unnamed: 0          0          1          2          3          4  \
0              0 -300.55713  41.210747 -28.552607  18.159660 -12.053949   
1              1 -427.00290  71.920680   2.438960  -9.972490  13.015941   
2              2 -441.80252  92.968930  18.334127 -13.860087  -4.942404   
3              3 -515.40280  60.018850  16.055157  11.454870  16.671350   
4              4 -294.87326  42.454680 -16.164543  16.639230   0.383591   
...          ...        ...        ...        ...        ...        ...   
2795        2795 -535.65580  82.136340  31.404861  10.432503  18.656220   
2796        2796 -417.77930  47.114150   4.027401   1.140913  -6.016336   
2797        2797 -498.90320  86.577260  19.229626   4.309079   6.996349   
2798        2798 -458.42746  75.567665  13.048701  -2.687592   0.343457   
2799        2799 -457.89777  81.758720  12.312971  -4.947131  12.314807   

              5          6          7          8  ...        29        30  \
0    -13.014520  -7.474535 -16.613626   4.596781  ...  0.233294 -0.029295   
1      6.249326 -16.573395   0.433565 -11.927688  ... -0.087143  0.324991   
2      3.462335 -10.084094   2.987232 -16.898640  ...  0.274595  0.017217   
3      9.852842  -7.672181  -7.884315 -11.110002  ... -0.080076  0.198389   
4     -8.516308 -13.656072  -8.207828  -6.559240  ...  0.308947 -0.119029   
...         ...        ...        ...        ...  ...       ...       ...   
2795  17.376785 -11.590422 -14.559093 -17.484442  ...  0.152236  0.089078   
2796  -0.087306 -14.628019  -0.596290 -16.090271  ...  0.207472  0.714745   
2797  11.253559  -2.563979  -7.855795 -12.648978  ... -0.094712  0.071911   
2798  -1.296336 -19.453487   1.916076 -14.151071  ...  0.043027 -0.004627   
2799   4.978829 -12.010356   2.655616  -9.685156  ...  0.086368  0.205741   

            31        32        33        34        35        36        37  \
0     0.058777  0.049846  0.185916  0.004312  0.012882  0.037445 -0.042841   
1     0.054818 -0.059586  0.097741 -0.109916 -0.024241  0.142814 -0.074044   
2    -0.184488 -0.059992 -0.103758  0.078861  0.223875  0.072165  0.089541   
3     0.269932  0.118826  0.089234  0.049660 -0.007672  0.040026 -0.075465   
4     0.179678 -0.107945 -0.002977  0.077969 -0.015562  0.019324  0.006253   
...        ...       ...       ...       ...       ...       ...       ...   
2795  0.123553  0.083157 -0.128567  0.044863  0.043942  0.043441  0.046708   
2796  0.065412  0.116629 -0.271002  0.042442  0.033315  0.017825  0.143210   
2797  0.149898  0.151957  0.084544  0.171150  0.089723  0.166517 -0.065117   
2798 -0.158036 -0.159278 -0.126592 -0.045731  0.157288 -0.098004 -0.015580   
2799  0.059922  0.129424  0.179931  0.099254  0.231199  0.197715  0.056402   

            38  
0     0.053880  
1    -0.054615  
2    -0.024524  
3    -0.016834  
4    -0.033961  
...        ...  
2795 -0.051097  
2796  0.111193  
2797 -0.003377  
2798  0.128801  
2799  0.059353  

[2800 rows x 40 columns]

In [213]:
np.mean(x["0"])

-406.9831301107139

In [214]:
np.std(x["0"])

67.47665311455476

In [215]:
x

Unnamed: 0          0          1          2          3          4  \
0              0 -300.55713  41.210747 -28.552607  18.159660 -12.053949   
1              1 -427.00290  71.920680   2.438960  -9.972490  13.015941   
2              2 -441.80252  92.968930  18.334127 -13.860087  -4.942404   
3              3 -515.40280  60.018850  16.055157  11.454870  16.671350   
4              4 -294.87326  42.454680 -16.164543  16.639230   0.383591   
...          ...        ...        ...        ...        ...        ...   
2795        2795 -535.65580  82.136340  31.404861  10.432503  18.656220   
2796        2796 -417.77930  47.114150   4.027401   1.140913  -6.016336   
2797        2797 -498.90320  86.577260  19.229626   4.309079   6.996349   
2798        2798 -458.42746  75.567665  13.048701  -2.687592   0.343457   
2799        2799 -457.89777  81.758720  12.312971  -4.947131  12.314807   

              5          6          7          8  ...        29        30  \
0    -13.014520  -7.474535 -16.613626   4.596781  ...  0.233294 -0.029295   
1      6.249326 -16.573395   0.433565 -11.927688  ... -0.087143  0.324991   
2      3.462335 -10.084094   2.987232 -16.898640  ...  0.274595  0.017217   
3      9.852842  -7.672181  -7.884315 -11.110002  ... -0.080076  0.198389   
4     -8.516308 -13.656072  -8.207828  -6.559240  ...  0.308947 -0.119029   
...         ...        ...        ...        ...  ...       ...       ...   
2795  17.376785 -11.590422 -14.559093 -17.484442  ...  0.152236  0.089078   
2796  -0.087306 -14.628019  -0.596290 -16.090271  ...  0.207472  0.714745   
2797  11.253559  -2.563979  -7.855795 -12.648978  ... -0.094712  0.071911   
2798  -1.296336 -19.453487   1.916076 -14.151071  ...  0.043027 -0.004627   
2799   4.978829 -12.010356   2.655616  -9.685156  ...  0.086368  0.205741   

            31        32        33        34        35        36        37  \
0     0.058777  0.049846  0.185916  0.004312  0.012882  0.037445 -0.042841   
1     0.054818 -0.059586  0.097741 -0.109916 -0.024241  0.142814 -0.074044   
2    -0.184488 -0.059992 -0.103758  0.078861  0.223875  0.072165  0.089541   
3     0.269932  0.118826  0.089234  0.049660 -0.007672  0.040026 -0.075465   
4     0.179678 -0.107945 -0.002977  0.077969 -0.015562  0.019324  0.006253   
...        ...       ...       ...       ...       ...       ...       ...   
2795  0.123553  0.083157 -0.128567  0.044863  0.043942  0.043441  0.046708   
2796  0.065412  0.116629 -0.271002  0.042442  0.033315  0.017825  0.143210   
2797  0.149898  0.151957  0.084544  0.171150  0.089723  0.166517 -0.065117   
2798 -0.158036 -0.159278 -0.126592 -0.045731  0.157288 -0.098004 -0.015580   
2799  0.059922  0.129424  0.179931  0.099254  0.231199  0.197715  0.056402   

            38  
0     0.053880  
1    -0.054615  
2    -0.024524  
3    -0.016834  
4    -0.033961  
...        ...  
2795 -0.051097  
2796  0.111193  
2797 -0.003377  
2798  0.128801  
2799  0.059353  

[2800 rows x 40 columns]

In [216]:
(x["0"]-np.mean(x["0"]))/np.std(x["0"])

0       1.577227
1      -0.296692
2      -0.516021
3      -1.606773
4       1.661462
          ...   
2795   -1.906921
2796   -0.159999
2797   -1.362250
2798   -0.762402
2799   -0.754552
Name: 0, Length: 2800, dtype: float64

In [217]:
x.shape

(2800, 40)

In [218]:
def normalize(x):
    arr=[]
    for i in range(x.shape[1]-1):
        x[str(i)]=(x[str(i)]-np.mean(x[str(i)]))/np.std(x[str(i)])
        arr.append((np.mean(x[str(i)]),np.std(x[str(i)])))
    return arr,x
    

In [219]:
arr,x=normalize(x)

In [220]:
x

Unnamed: 0         0         1         2         3         4         5  \
0              0  1.577227 -0.826372 -2.204632  0.573316 -0.766108 -2.024356   
1              1 -0.296692  0.550296 -0.229781 -1.266972  1.400507  0.717585   
2              2 -0.516021  1.493848  0.783095 -1.521283 -0.151507  0.320895   
3              3 -1.606773  0.016759  0.637874  0.134716  1.716418  1.230495   
4              4  1.661462 -0.770609 -1.415237  0.473856  0.308781 -1.384098   
...          ...       ...       ...       ...       ...       ...       ...   
2795        2795 -1.906921  1.008244  1.615991  0.067837  1.887956  2.301424   
2796        2796 -0.159999 -0.561734 -0.128562 -0.539980 -0.244319 -0.184347   
2797        2797 -1.362250  1.207322  0.840158 -0.332732  0.880276  1.429868   
2798        2798 -0.762402  0.713783  0.446295 -0.790425  0.305313 -0.356435   
2799        2799 -0.754552  0.991316  0.399413 -0.938234  1.339913  0.536747   

             6         7         8  ...        29        30        31  \
0     0.166922 -1.063399  2.160333  ...  0.588573 -0.649177  0.293894   
1    -1.199183  1.091509 -0.238900  ... -1.077871  1.333875  0.255897   
2    -0.224878  1.414314 -0.960645  ...  0.803365 -0.388839 -2.040581   
3     0.137247  0.040059 -0.120178  ... -1.041119  0.625245  2.320221   
4    -0.761176 -0.000836  0.540560  ...  0.982014 -1.151452  1.454108   
...        ...       ...       ...  ...       ...       ...       ...   
2795 -0.451038 -0.803689 -1.045700  ...  0.167032  0.013395  0.915507   
2796 -0.907104  0.961327 -0.843276  ...  0.454287  3.515462  0.357560   
2797  0.904194  0.043664 -0.343626  ... -1.117232 -0.082694  1.168319   
2798 -1.631601  1.278911 -0.561719  ... -0.400918 -0.511104 -1.786738   
2799 -0.514087  1.372395  0.086700  ... -0.175520  0.666396  0.304878   

            32        33        34        35        36        37        38  
0     0.132706  1.464388 -0.603413 -0.014121  0.085438 -0.645746  0.319027  
1    -0.782570  0.630771 -1.893425 -0.428726  1.259525 -1.051582 -1.112429  
2    -0.785970 -1.274210  0.238489  2.342275  0.472315  1.076037 -0.715413  
3     0.709651  0.550348 -0.091290 -0.243681  0.114202 -1.070069 -0.613951  
4    -1.187036 -0.321419  0.228408 -0.331792 -0.116471 -0.007230 -0.839927  
...        ...       ...       ...       ...       ...       ...       ...  
2795  0.411322 -1.508757 -0.145462  0.332757  0.152248  0.518940 -1.066007  
2796  0.691277 -2.855336 -0.172810  0.214077 -0.133170  1.774075  1.075211  
2797  0.986754  0.506005  1.280729  0.844048  1.523638 -0.935486 -0.436401  
2798 -1.616388 -1.490083 -1.168565  1.598619 -1.423812 -0.291191  1.307526  
2799  0.798296  1.407803  0.468785  2.424063  1.871269  0.645027  0.391237  

[2800 rows x 40 columns]

In [221]:
x

Unnamed: 0         0         1         2         3         4         5  \
0              0  1.577227 -0.826372 -2.204632  0.573316 -0.766108 -2.024356   
1              1 -0.296692  0.550296 -0.229781 -1.266972  1.400507  0.717585   
2              2 -0.516021  1.493848  0.783095 -1.521283 -0.151507  0.320895   
3              3 -1.606773  0.016759  0.637874  0.134716  1.716418  1.230495   
4              4  1.661462 -0.770609 -1.415237  0.473856  0.308781 -1.384098   
...          ...       ...       ...       ...       ...       ...       ...   
2795        2795 -1.906921  1.008244  1.615991  0.067837  1.887956  2.301424   
2796        2796 -0.159999 -0.561734 -0.128562 -0.539980 -0.244319 -0.184347   
2797        2797 -1.362250  1.207322  0.840158 -0.332732  0.880276  1.429868   
2798        2798 -0.762402  0.713783  0.446295 -0.790425  0.305313 -0.356435   
2799        2799 -0.754552  0.991316  0.399413 -0.938234  1.339913  0.536747   

             6         7         8  ...        29        30        31  \
0     0.166922 -1.063399  2.160333  ...  0.588573 -0.649177  0.293894   
1    -1.199183  1.091509 -0.238900  ... -1.077871  1.333875  0.255897   
2    -0.224878  1.414314 -0.960645  ...  0.803365 -0.388839 -2.040581   
3     0.137247  0.040059 -0.120178  ... -1.041119  0.625245  2.320221   
4    -0.761176 -0.000836  0.540560  ...  0.982014 -1.151452  1.454108   
...        ...       ...       ...  ...       ...       ...       ...   
2795 -0.451038 -0.803689 -1.045700  ...  0.167032  0.013395  0.915507   
2796 -0.907104  0.961327 -0.843276  ...  0.454287  3.515462  0.357560   
2797  0.904194  0.043664 -0.343626  ... -1.117232 -0.082694  1.168319   
2798 -1.631601  1.278911 -0.561719  ... -0.400918 -0.511104 -1.786738   
2799 -0.514087  1.372395  0.086700  ... -0.175520  0.666396  0.304878   

            32        33        34        35        36        37        38  
0     0.132706  1.464388 -0.603413 -0.014121  0.085438 -0.645746  0.319027  
1    -0.782570  0.630771 -1.893425 -0.428726  1.259525 -1.051582 -1.112429  
2    -0.785970 -1.274210  0.238489  2.342275  0.472315  1.076037 -0.715413  
3     0.709651  0.550348 -0.091290 -0.243681  0.114202 -1.070069 -0.613951  
4    -1.187036 -0.321419  0.228408 -0.331792 -0.116471 -0.007230 -0.839927  
...        ...       ...       ...       ...       ...       ...       ...  
2795  0.411322 -1.508757 -0.145462  0.332757  0.152248  0.518940 -1.066007  
2796  0.691277 -2.855336 -0.172810  0.214077 -0.133170  1.774075  1.075211  
2797  0.986754  0.506005  1.280729  0.844048  1.523638 -0.935486 -0.436401  
2798 -1.616388 -1.490083 -1.168565  1.598619 -1.423812 -0.291191  1.307526  
2799  0.798296  1.407803  0.468785  2.424063  1.871269  0.645027  0.391237  

[2800 rows x 40 columns]

In [222]:
y

array([5, 2, 5, ..., 1, 5, 2])

In [223]:
import sklearn

In [224]:
from sklearn.svm import SVC

In [225]:
from sklearn.model_selection import train_test_split

In [226]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=1)

In [227]:
x_train.shape

(1876, 40)

In [228]:
x_test.shape

(924, 40)

In [229]:
y_train.shape

(1876,)

In [230]:
y_test.shape

(924,)

In [355]:
clf=SVC(C=700, kernel='rbf', degree=3,gamma=0.00002)

In [356]:
clf.fit(x_train,y_train)

SVC(C=700, gamma=2e-05)

In [357]:
prediction=clf.predict(x_test)

In [358]:
np.mean(prediction==y_test)*100

75.97402597402598

In [359]:
import pickle

In [360]:
with open('svm_tess','wb') as f:
    pickle.dump(clf, f)